import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { HeroProviders } from "./HeroProviders";
import Navigation from "@/components/Navigation";
import { WalletProviders } from "./WalletProviders";
import { getConfig } from "./wagmi";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get('cookie'),
  )
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <HeroProviders>
            <WalletProviders initialState={initialState}>
            <Navigation/>
          {children}
            </WalletProviders>
          </HeroProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
